permissions:
  guildmod-disband: 'runicadmin.guilds.disband'
  guildmod-kick: 'runicadmin.guilds.kick'
  guildmod-reset: 'runicadmin.guilds.reset'
  guildmod-bank: 'runicadmin.guilds.bank'
max-bank-pages: 10
guild-heralds:
  - 477 # dmr
guild-cost: 64