name: RunicGuilds
description: Runic Realms Guilds Plugin, by Excel
version: 1.0
main: com.runicrealms.runicguilds.Plugin
api-version: 1.13
commands:
  guild:
    description: Command for guild operations
  guildmod:
    description: Command for guild moderator operations