max-bank-pages: 5
banners:
  number1:
    world: 'world'
    x: 0
    y: 0
    z: 0
    yaw: 0
  number2:
    world: 'world'
    x: 0
    y: 0
    z: 0
    yaw: 0
  number3:
    world: 'world'
    x: 0
    y: 0
    z: 0
    yaw: 0
guild-heralds:
  - 313 # Azana
  - 476 # Koldore
  - 662 # Hilstead
  - 478 # Wintervale
  - 477 # DMR
  - 663 # Isfodar
  - 479 # Zenyth
  - 480 # Naheen
  - 481 # Naz'mora
  - 729 # Stonehaven
guild-bankers:
  - 714 # Azana
  - 715 # Azana
  - 716 # Koldore
  - 717 # Hilstead
  - 718 # Wintervale
  - 719 # DMR
  - 720 # Isfodar
  - 721 # Zenyth
  - 722 # Naheen
  - 723 # Naz'mora
  - 725 # Stonehaven
time-challengers:
  - 46
  - 47
  - 48
  - 49
  - 50
dungeon-bosses:
  - 'GoblinBossEnraged'
  - 'Odin'
  - 'TheLibrarian'
  - 'DeraPharaoh'
  - 'Eldrid'
guild-cost: 1500
