name: RunicGuilds
description: Runic Realms Guilds Plugin, by Excel
version: 1.0
main: com.runicrealms.runicguilds.Plugin
api-version: 1.13
softdepend: [PlaceholderAPI, RunicRestart, HolograpicDisplays]
commands:
  guild:
    description: Command for guild operations
  guildmod:
    description: Command for guild moderator operations
  forcereloadbanners:
    description: Command for guild operations
  makeguildbanner:
    description: Command for guild moderator operations
Permissions:
  permissions.guild-mod-disband:
    description: Allows a moderator to force disband guilds
  permissions.guild-mod-kick:
    description: Allows a moderator to force kick players from guilds
  permissions.guild-mod-reset:
    description: Allows a moderator to reset guild scores
  permissions.guild-mod-bank:
     description: Allows a moderator to access a guild's bank
  permissions.guild-mod-giveexp:
    description: Allows a moderator to give a player guild exp