name: RunicGuilds
description: Runic Realms Guilds RunicGuilds, by Excel
version: 1.0
main: com.runicrealms.runicguilds.RunicGuilds
api-version: 1.13
softdepend: [ PlaceholderAPI, RunicRestart, HolograpicDisplays, RunicChat, RunicCommon ]
Permissions:
  permissions.guild-mod:
    description: Allows a moderator to execute guildmod command
  permissions.guild-mod-disband:
    description: Allows a moderator to force disband guilds
  permissions.guild-mod-kick:
    description: Allows a moderator to force kick players from guilds
  permissions.guild-mod-reset:
    description: Allows a moderator to reset guild scores
  permissions.guild-mod-bank:
    description: Allows a moderator to access a guild's bank
  permissions.guild-mod-giveexp:
    description: Allows a moderator to give a player guild exp
  permissions.guild-mod-givescore:
    description: Allows a moderator to give a player guild score